### ISSUE TITLE
world/scripts doesn't get loaded

### ISSUE THREAD

**Issue by Sir-Will** [jaredlll08/FTBTweaks#1]
hey, 

it seems that the scripts in the world folder don't get loaded if FTBTweaks is installed.
Would be great if this gets fixed as we need it to send recipes from the server to the client.

Edit: Same issue with the scripts folder in the main folder.

**Comment by jaredlll08** [comment]
What do you mean by "scripts in the world folder", where are you putting the scripts?

**Comment by Sir-Will** [comment]
Minetweaker creates a script folder inside the world folder.
From the wiki:

> The world-specific script directory: this directory is also called scripts, but is stored in the savegame directory (world/scripts if you are setting up a dedicated server)
> http://minetweaker3.powerofbytes.com/wiki/Tutorial:Introduction#Scripts

**Comment by jaredlll08** [comment]
uh, I don't think we can do anything about that, it seems kinda useless since using FTBTweaks, you could replicate the same thing...
Could you give me a use of this? like, I have cleaned out both the Minetweaker and the Modtweaker issue list, and have never seen anyone using world/scripts

**Comment by Sir-Will** [comment]
We have custom recipes on the server and that the client can see the recipes we place them into the world/scripts folder as minetweaker does send them to the client but since the update which added FTBTweaks it does no longer get loaded.

**Comment by jaredlll08** [comment]
You could just put it in the /scripts/ directory, but with FTBTweaks, you should just put the custom scripts into the recipe mode that you play in

**Comment by Sir-Will** [comment]
The default scripts folder doesn't send the recipes to the client as you can read on the wiki page and the scripts in that folder don't get loaded too as I wrote above.

I didn't try to add them to the FTBTweaks directory yet but I don't think they get send to the client or?

**Comment by jaredlll08** [comment]
They should get sent to the client, but you should NEVER use server only scripts in the long term solution.

**Comment by Sir-Will** [comment]
Ok it works in the modpack/mode/scripts directory.

Well I can't edit the official FTB pack to add an recipe so I can do it only serverside.

Is there a reason why the default scripts folders get ignored? I mean as modpack creator you could place global, for all modes, recipes into them.

**Comment by jaredlll08** [comment]
I just gets ignored because of our reload, not sure if there is anything I can do about that.

**Comment by LatvianModder** [comment]
Global for all modes goes into /modpack/common/scripts if you really want that
