### ISSUE TITLE
Request: multiple modes that can be toggled independently

### ISSUE THREAD

**Issue by TheDeviantCrafter** [jaredlll08/FTBTweaks#13]
I'd like to be able to create multiple pack mode settings. Each one would have a folder of scripts which can be toggled on and off independently from all of the others.

This can give player more fine-tuned control over various pack settings involving recipes. For example, a pack could add the following:

- Peaceful recipes: Adds recipes to all hostile mob drops if people don't enjoy combat

- Harder transportation: Disables all forms of item teleportation and requires the player to lay rails and trains for long distance transportation

- Harder food: Disables most of the easily-accessible food options for players who enjoy that challenge

- No worries: Adds recipes to normally disabled items that make hunger, sleep, and combat unnecessary so they can focus on building

**Comment by LatvianModder** [comment]
~~That is *literally* what this mod is about, what are you even requesting?~~ Oh, I see.. multiple at *the same time*. But either way, this mod is long dead and can't even be updated to newer versions, because recipe reloading no longer can be done, correct me if I'm wrong, Jared.

**Comment by jaredlll08** [comment]
Not wrong.
