### ISSUE TITLE
Auto Crafting Tables crash on startup if the game mode is not set to normal

### ISSUE THREAD

**Issue by pkmnfrk** [jaredlll08/FTBTweaks#2]
I just started getting into Logistics pipes in FTB Infinity Evolved, Expert mode. This meant that I started plopping down a whole bunch of Auto Crafting tables. Everything was fine, and I shut the game down to do something else. Later, I came back, and every time I loaded the world, it would crash.

https://gist.github.com/pkmnfrk/6840a562795f1eeaf674

After racking my brain trying everything, I thought about what was causing the error, and thought "maybe Buildcraft is trying to iterate recipes, while FTB Tweaks was changing them?". To test it, I edited gamemodes.json and removed "expert". This caused my world to reset to normal and load properly.

Then I did "/ftb_mode set normal" (to reset the internal state) and quit. I re-enabled "expert", and reloaded the game, and it still loaded. Then, in game, I ran "/ftb_mode set expert", and confirmed that it worked correctly.

Not sure if this is technically a Buildcraft or FTBTweaks issue, but I suspect the latter

**Comment by jaredlll08** [comment]
This is a buildcraft issue
