### ISSUE TITLE
mod compatibility request

### ISSUE THREAD

**Issue by Cazadorsniper** [jaredlll08/FTBTweaks#4]
Is it possible to add Ingame Config Manager as a mod that can change recipes and utilize the other mode creation instead of just minetweaker?

**Comment by jaredlll08** [comment]
Well scripts are not configs. Also please elaborate more on what you want.

**Comment by Cazadorsniper** [comment]
I want to use Ingame Config manager to change recipes rather than Minetweaker and I have asked CreativeMD if it was possible to have separate files for recipes to use in a different modes.

**Comment by jaredlll08** [comment]
uh what, I have no idea what you are on about, once again, scripts are NOT configs, I can't find any information on "Ingame Config Manager".

**Comment by Cazadorsniper** [comment]
I know they are not configs I've kind of used minetweaker before I just rather use Ingameconfigmanager for recipe changes. Have to search up the mod put together like I just did.

**Comment by jaredlll08** [comment]
I just did search up the mod, I found the authors page, no mod there, if you provide no info, then the answer is no, you have provided no info.

**Comment by Cazadorsniper** [comment]
here is its minecraftforum page: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2518796-ingameconfigmanager-v0-1-10-modify-your-config

here is its Github: https://github.com/CreativeMD/InGameConfigManager

**Comment by Cazadorsniper** [comment]
i just want to know is it possible to use FTBTweaks without minetweaker

**Comment by jaredlll08** [comment]
It is not, it depends on Minetweaker.

**Comment by Cazadorsniper** [comment]
ok

**Comment by Cazadorsniper** [comment]
well i guess ill use both xD
