### ISSUE TITLE
[Question] How do I actually add minetweaker scripts to this mod?

### ISSUE THREAD

**Issue by GazbonicAcid** [jaredlll08/FTBTweaks#6]
How do I add minetweaker scripts for the gamemodes from the version of FTB Tweaks for 1.10.2 released today?
[Copy/Paste](https://minecraft.curseforge.com/projects/ftb-tweaks?comment=24)

**Comment by jaredlll08** [comment]
I replied to you in the curse pm. DO NOT SPAM ME!

**Comment by GazbonicAcid** [comment]
I looked at other modpacks that make use of it.
Their method does not work in the first 1.10.2 release of FTBTweaks.

**Comment by GazbonicAcid** [comment]
Also, sorry for spamming...
I hope that you can look past it to help me get this to work,
or to fix a bug if it's a bug/error making it not work.

**Comment by jaredlll08** [comment]
well what part of their stuff isn't working?

**Comment by GazbonicAcid** [comment]
the loading of scripts.
It's specifically just loading the gamemode minetweaker scripts that isn't working.
I haven't tried any other features in particular though.

**Comment by jaredlll08** [comment]
well you are not providing any detail, the scripts for example, the packmodes.json/gamemodes.json of any info like that

**Comment by GazbonicAcid** [comment]
sorry about that, I'll get to it right away.

**Comment by GazbonicAcid** [comment]
[Game-Instance-Dir/modpack/packmodes.json](http://hastebin.com/gijibadiho.json)
[Game-Instance-Dir/modpack/netheron/scripts/Changes.zs](http://hastebin.com/saximenaye.xml)
[Game-Instance-Dir/modpack/normal/scripts/Changes.zs](http://hastebin.com/goyiyusazo.xml)
[Logs and /modpack/ folder from all attempts current and yet to be posted.](https://drive.google.com/open?id=0B3j9je-_qiwhVEtrUjhHeWZfSEE).
Ignore the bit about FTGU, after I removed From The Ground Up I forgot to remove the minetweaker script I was using to play around with its new minetweaker support.

Second Attempt
[Game-Instance-Dir/modpack/packmodes.json](http://hastebin.com/gijibadiho.json)
[Game-Instance-Dir/modpack/netheron/Changes.zs](http://hastebin.com/saximenaye.xml)
[Game-Instance-Dir/modpack/normal/Changes.zs](http://hastebin.com/goyiyusazo.xml)

Third Attempt
[Game-Instance-Dir/modpack/packmodes.json](http://hastebin.com/gijibadiho.json)
[Game-Instance-Dir/modpack/netheron.zs](http://hastebin.com/saximenaye.xml)
[Game-Instance-Dir/modpack/normal.zs](http://hastebin.com/goyiyusazo.xml)

**Comment by majix560** [comment]
[Game-Instance-Dir/modpack/packmodes.json](http://hastebin.com/gijibadiho.json)
[Game-Instance-Dir/modpack/netheron/Changes.zs](http://hastebin.com/saximenaye.xml)
[Game-Instance-Dir/modpack/normal/Changes.zs](http://hastebin.com/goyiyusazo.xml)

**Comment by GazbonicAcid** [comment]
All three times, none of the scripts load/activate and recipes remain unchanged.
And yes, all three times all three of the files' contents remain exactly the same.

**Comment by GazbonicAcid** [comment]
Let me know when you've figured this out.
Until then I'll assume you're too busy to reply here at the moment.
And yes, I know you have irl obligations and other stuff to work on.

**Comment by GazbonicAcid** [comment]
I would like to know why you closed this issue.
I mean after all, you haven't released a fix for it.

**Comment by GazbonicAcid** [comment]
Because after looking through FTBTweaks' source code, the stuff I've tried should have worked...and yet it didn't.
