### ISSUE TITLE
Don't enable mod if mod is missing on the server

### ISSUE THREAD

**Issue by Sir-Will** [jaredlll08/FTBTweaks#8]
hey,
it would be great if the mod doesn't enable if the mod is not enabled on the server the player is connecting too.
At the moment it causes the recipes not to load until someone runs /mt reload.
This is the same/similar issue I reported for 1.7.10 here: https://github.com/jaredlll08/FTBTweaks/issues/1

**Comment by Sir-Will** [comment]
Ups, linked the wrong issue. That's the one I meant to link: https://github.com/LatvianModder/FTBLib/issues/20

**Comment by jaredlll08** [comment]
Not going to happen. so from what I understand, you want to make it that if the mod is not on the server, it doesn't do anything on the client, then the client won't have the scripts.
If that happens, the client wont get the updated recipes and I just get more bug reports.
